sudo: false

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: mvn -B -U install

script: travis_wait 60 mvn -B -U -Dmaven.javadoc.skip=true verify

cache:
  directories:
  - $HOME/.m2

